import Nav from "./nav";
import Head from "next/head";

const layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>{}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      {children}
      <footer className="fixed  bg-blue-400 text-white w-screen font-bold p-2 inset-x-0 bottom-0  opacity-10 hover:opacity-100 duration-100 ">
        Copyright &copy; {new Date().getFullYear()}
      </footer>
    </>
  );
};

export default layout;
